version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ihelp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ihelp
      POSTGRES_USER: ihelpuser
      POSTGRES_PASSWORD: ihelppassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
